### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by rijkvanzanten** [VincentKempers/boilerplate-vue-typescript-setup#1]
We don't want those sneaky sneaky files sneaking into to the repo now do we.

![](https://media.giphy.com/media/3PAGDqG9ENQF8QHZKt/giphy.gif)

**Comment by VincentKempers** [comment]
OH
![oh Fyuck](https://i.kym-cdn.com/photos/images/original/001/455/831/7bc.jpg)
